# Site
title: Inaheaven
description: Personal Portfolio
url: https://inaheaven.github.io/Home-Org2
logo: /logo/inaheaven_logo.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/background/background_6.jpeg                           # this image will be shown on homepage's left block
  post-list: images/background/background_9.jpeg             # this image will be shown on post list page
  default-post: images/background/background_11.jpeg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:categories/:year/:month/:day/:title
markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate-v2
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
email:              sangmin.rim@gmail.com
#google.plus:        username
#twitter:            username
#facebook:           username
github:             inaheaven
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems Has Been Deprecated
#gems:
#  - jekyll-feed
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-paginate-v2

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]


# Pagination Settings
pagination:
  enabled: true
  per_page: 4
  sort_reverse: true
  trail:
    before: 2
    after: 2


